### ISSUE TITLE
"Гит сошел с ума"

### ISSUE THREAD

**Issue by comma** [solarisstation/Baystation12#1]
Здравствуйте россияне я пришел с миром с бея, потому что заметил
https://github.com/Baystation12/Baystation12/pull/15697
Скорее всего вы ебетесь с неебическим количеством замен LF->CLRF из https://github.com/Baystation12/Baystation12/pull/15659
Автор этого советует что самый простой способ спастись это ревертнуть эти два коммита.
По идее гитовые клиенты должны без проблем мержить конфликты где изменились только newlines, но на деле как повезет.

**Comment by Unicode4all** [comment]
Спасибо за информацию. Я, кажись, зря волновался.

**Comment by Unicode4all** [comment]
b7faaf01162576f924d9d7791356da683774e7e9

Вроде все работает
