### ISSUE TITLE
Спрайтопроблемы

### ISSUE THREAD

**Issue by RandomColonist** [solarisstation/Baystation12#13]
Значит, поиграл я малёха на вашем сервере. Первое, что бросилось мне в глаза - эрисовские спрайты. Дело в том, что спрайты с Эриса очень плохо сочетаются с дефолтными спрайтами бея. В частности, речь идёт о некоторых тайлах, консолях, слипперах и криокапсулах из дорм (криокапсулы, которые вообще на несколько тонов темнее, чем окружающие спрайты). Выглядит это всё, мягко говоря, вырвиглазно. К тому же, множество консолей повёрнуто вообще не в ту сторону. Варианты решения проблемы - вы либо ВСЕ спрайты с эриса пиздите, либо только некоторые, которые так сильно в глаза не бросаются. Глаза вытекают.

**Comment by Sammaell** [comment]
Я просил маппера поменять в паре мест полы и повернуть консоли - Торч не открывается.

**Comment by RandomColonist** [comment]
Так себе у вас маппер. Консоли и полы - ещё пол беды.

**Comment by Euronem** [comment]
кек

**Comment by SpadesSlick** [comment]
Русский девелопмент, бессмысленный и беспощадный.

**Comment by seekin4u** [comment]
Вам че, клокриггер опять начал ныть что "кококо спиздили спрайты так некрасиво" ?

**Comment by SpadesSlick** [comment]
@seekin4u
>указали на неуместность частичного пиздинга, потому что стили не сходятся
>кококок делаю что хочу копирайтом не запрещено

**Comment by Sammaell** [comment]
Мы благородные пираты семи билдов.

**Comment by RandomColonist** [comment]
Да пиздите на здоровье, лол, если вам своих глаз не жалко. Ни о каком ебучем копирайте речь даже не шла.
